@Library('Shared') _
pipeline{
  agent { label 'azureuser'}

  stages{
    stage('Cleaning workspace'){
      steps{
        script{
          cleanWorkspace()
        }
      }
    }
    stage('Cloning code from repo'){
      steps{
        script{
          gitClone("https://github.com/Umerfarooqsyed/MERN-DevSecOps-Project.git","main")
        }
      }
    }
    stage('OWASP dependency check'){
      steps{
        script{
          owaspDependencyCheck()
        }
      }
    }
    stage('SonarQube Static Code Analysis'){
      environment{
        SONAR_HOME = tool "Sonar"
      }
      steps{
        script{
          sonarQubeCodeAnalysis("MySonarServer","backend","backend")
        }
      }
    }
    stage('SonarQube Code Quality Gate Check'){
      steps{
        script{
          sonarQubeQualityGate()
        }
      }
    }
    stage('trivyFsScan'){
      steps{
        script{
          trivyFsScan()
        }
      }
    }
    stage('building docker image'){
      steps{
        script{
          dockerBuild("umerfarooqsyed/mern-devsecops-project","backend-Version-${env.BUILD_NUMBER}")
        }
      }
    }
    stage('pushing new image to docker hub'){
      steps{
        script{
          dockerPush("umerfarooqsyed/mern-devsecops-project","backend-Version-${env.BUILD_NUMBER}")
        }
      }
    }
    stage('updating new image version on kubernetes manifest files'){
      environment {
        GITHUB_TOKEN= credentials('github-token')
        GIT_USER_NAME= "Umerfarooqsyed"
        GIT_USER_EMAIL= "umerfarooqsyed18@gmail.com"
        GIT_REPO_NAME= "MERN-DevSecOps-Project"
        LATEST_IMAGE= "umerfarooqsyed/mern-devsecops-project:backend-Version-${env.BUILD_NUMBER}"
    }
      steps{
        sh '''
        chmod +x /scripts/update-k8s-manifest.sh
        ./update-k8s-manifest.sh frontend
        '''
      }
    }
  }
}
